export const ADMIN_USER_LIST_SUCCESS = 'ADMIN_USER_LIST_SUCCESS';
export const ADMIN_USER_LIST_ERROR = 'ADMIN_USER_LIST_ERROR';

export const ADMIN_USER_BY_ID_SUCCESS = 'ADMIN_USER_BY_ID_SUCCESS';
export const ADMIN_USER_BY_ID_ERROR = 'ADMIN_USER_BY_ID_ERROR';

export const ADMIN_USER_ADD_SUCCESS = 'ADMIN_USER_ADD_SUCCESS';
export const ADMIN_USER_ADD_ERROR = 'ADMIN_USER_ADD_ERROR';

export const ADMIN_USER_RESUME_EDIT_SUCCESS = 'ADMIN_USER_RESUME_EDIT_SUCCESS';
export const ADMIN_USER_RESUME_EDIT_ERROR = 'ADMIN_USER_RESUME_EDIT_ERROR';

export const ADMIN_USER_DELETE_SUCCESS = 'ADMIN_USER_DELETE_SUCCESS';
export const ADMIN_USER_DELETE_ERROR = 'ADMIN_USER_DELETE_ERROR';

export const ADMIN_USER_SEE = 'ADMIN_USER_SEE';

