export const USER_ME_SUCCESS = 'USER_ME_SUCCESS';
export const USER_ME_ERROR = 'USER_ME_ERROR';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';

export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';

export const USER_LOGOUT = 'USER_LOGOUT';
